### ISSUE TITLE
#enhancement

### ISSUE THREAD

**Issue by kalamhavij** [matagus/django-planet#16]
It would be nice if there was a feedmanager part. So each user could manage his/her feeds (add/remove ...) them. I mean like Google Reader. 

I mean something like allowing users to create subscription lists. take a look at please.

[Model] (https://github.com/overshard/sorbet/blob/master/sorbet/feedmanager/models.py)
Thanks

**Comment by matagus** [comment]
closing this in favor of #35 and #36, thanks for submitting this idea
