### ISSUE TITLE
demo down

### ISSUE THREAD

**Issue by COLABORATI** [matagus/django-planet#65]
demo site gives a 500 error. monitoring is a good thing.

**Comment by matagus** [comment]
Thanks for reporting this @COLABORATI 

The demo website is hosted in heroku using a free dyno: it has to sleep at least 6 hs, so when you see it's down that is the reason. Sorry but I can't afford to pay for a better dyno.

Just try again a few hours later.

**Comment by COLABORATI** [comment]
ah, ok, not a heroku customer so I did not know they require a downtime for their servers to be free. thanks for the info, have a nice day!
