### ISSUE TITLE
Install instructions do not work

### ISSUE THREAD

**Issue by COLABORATI** [matagus/django-planet#67]
The installation instructions do not work. Instead of describing all the different kind of errors and the long-winded trial and error process I went through I think it would make more sense if you just tried to follow the instructions yourself - you will see that it will not lead to a working installation of your project.

It would be a very good and important welcome step when new users could just follow the installation instructions successfully - a positive result is always very good for motivation. 

Additionally, instead of writing lots of text and make people copy-paste that text (that you have to maintain in the future) it would be much easier to simply provide an example project (or a setup script).

Thanks for your attention!

**Comment by matagus** [comment]
Planning to fix this issue tomorrow. I'll keep you posted. Thanks for reporting it @COLABORATI

**Comment by synw** [comment]
I refactored the doc, making it more user friendly. Mostly:
- Simplified the install instructions by removing all the classic Django setup instructions that everybody knows. This new doc is focused on an install as a module, not an install as a full site.
- Added a section for the auto update setup
- Added a section for the management commands

Its here: http://django-planet-continued.readthedocs.io/en/latest/install.html

**Comment by COLABORATI** [comment]
wow, thank you very much, will try this later, maybe tomorrow! Thanks!

**Comment by matagus** [comment]
Added a working [demo project](https://github.com/matagus/django-planet-demo) for Django 1.8.11 & python 3.5.1.
