### ISSUE TITLE
Website showing Internal Server error.

### ISSUE THREAD

**Issue by shankarj67** [matagus/django-planet#76]
Website is showing Internal server error, please check if there is a problem with Heroku or something else.

![screenshot 236](https://user-images.githubusercontent.com/11690680/36833583-ef13cf12-1d55-11e8-81b8-60d3a9a5698b.png)
![screenshot 237](https://user-images.githubusercontent.com/11690680/36833585-ef5dde4a-1d55-11e8-80fb-02a8bf509dd8.png)

**Comment by matagus** [comment]
Thanks for reporting it. It's now fixed and working.
